# Vanilla.PDF .NET CI/CD file

stages:
  - test
  - deploy

# Windows platform is still in development
# ====================================

windows-nanoserver-ltsc2022-test:
  image: mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-ltsc2022
  stage: test
  when: manual
  tags:
    - windows
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net6.0

# Ubuntu 20.04 - test, deploy
# ====================================

ubuntu-20.04-amd64-test:
  image: registry.gitlab.com/jurzik/vanillapdf-net/vanillapdf-ubuntu-amd64:20.04
  stage: test
  when: manual
  tags:
    - linux
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

ubuntu-20.04-amd64-deploy:
  image: registry.gitlab.com/jurzik/vanillapdf-net/vanillapdf-ubuntu-amd64:20.04
  stage: deploy
  when: manual
  needs: [ubuntu-20.04-amd64-test]
  tags:
    - linux
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "src/vanillapdf.net/bin/Release/*.nupkg" --source gitlab
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - src/vanillapdf.net/bin/Release/*.nupkg



# Currently the native libraries are built against OpenSSL 1.x,
# which is not supported on Ubuntu 22.04
# ====================================

ubuntu-22.04-amd64-test-disabled:
  image: registry.gitlab.com/jurzik/vanillapdf-net/vanillapdf-ubuntu-amd64:22.04
  stage: test
  when: manual
  tags:
    - linux
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591
