# Vanilla.PDF .NET CI/CD file

# Windows platform is still in development
windows-nanoserver-ltsc2022-test:
  image: mcr.microsoft.com/dotnet/sdk:6.0-nanoserver-ltsc2022
  when: manual
  tags:
    - windows
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net6.0

ubuntu-20.04-amd64-test:
  image: registry.gitlab.com/jurzik/vanillapdf-net/vanillapdf-ubuntu-amd64:20.04
  when: manual
  tags:
    - linux
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

ubuntu-22.04-amd64-test:
  image: registry.gitlab.com/jurzik/vanillapdf-net/vanillapdf-ubuntu-amd64:22.04
  when: manual
  tags:
    - linux
  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./*.nupkg
