# Vanilla.PDF .NET CI/CD file

stages:
  - test
  - deploy

# Windows - build
# ====================================

windows-ltsc2022-x86:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-windows-amd64:ltsc2022
  stage: test
  when: manual
  tags:
    - windows
    - private

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net8.0 --arch x86 -nowarn:CS1591

windows-ltsc2022-x64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-windows-amd64:ltsc2022
  stage: test
  when: manual
  tags:
    - windows
    - private

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net8.0 -nowarn:CS1591

# OSX - build
# ====================================

build-osx-x64:
  when: manual
  tags:
    - macos
    - private

  script:
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net8.0 -nowarn:CS1591

# Ubuntu 22.04
# ====================================

build-ubuntu.22.04-arm64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-ubuntu-arm64v8:22.04
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

build-ubuntu.22.04-x64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-ubuntu-amd64:22.04
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

# Ubuntu 24.04
# ====================================

build-ubuntu.24.04-arm64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-ubuntu-arm64v8:24.04
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net8.0 -nowarn:CS1591

build-ubuntu.24.04-x64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-ubuntu-amd64:24.04
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release --framework net8.0 -nowarn:CS1591

# rockylinux.8
# ====================================

build-rocky.8-arm64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-rockylinux-arm64v8:8
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

build-rocky.8-x64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-rockylinux-amd64:8
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

# rockylinux.9
# ====================================

build-rocky.9-arm64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-rockylinux-arm64v8:9
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

build-rocky.9-x64:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-rockylinux-amd64:9
  stage: test
  when: manual
  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet test src/vanillapdf.net.sln --configuration Release -nowarn:CS1591

nuget-deploy-staging:
  image: registry.gitlab.com/vanillapdf-group/vanillapdf-net/vanillapdf-net-ubuntu-amd64:22.04
  stage: deploy
  when: manual

  tags:
    - linux

  script:
    - dotnet nuget add source "${CI_API_V4_URL}/groups/61919871/-/packages/nuget/index.json" --name gitlab-group --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab-project --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet build src/vanillapdf.net.sln --configuration Release -nowarn:CS1591
    - dotnet nuget push "src/vanillapdf.net/bin/Release/*.nupkg" --source gitlab-project

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - src/vanillapdf.net/bin/Release/*.nupkg
