namespace vanillapdf.net.PdfContents
{
    /// <summary>
    /// Derived types of \ref PdfContentOperator
    /// </summary>
    public enum PdfContentOperatorType
    {
        /// <summary>
        /// Undefined unitialized default value, triggers error when used
        /// </summary>
        Undefined = 0,
        Unknown,
        LineWidth,
        LineCap,
        LineJoin,
        MiterLimit,
        DashPattern,
        ColorRenderingIntent,
        Flatness,
        GraphicsState,
        SaveGraphicsState,
        RestoreGraphicsState,
        TransformationMatrix,
        BeginSubpath,
        Line,
        FullCurve,
        FinalCurve,
        InitialCurve,
        CloseSubpath,
        Rectangle,
        Stroke,
        CloseAndStroke,
        FillPathNonzero,
        FillPathCompatibility,
        FillPathEvenOdd,
        FillStrokeNonzero,
        FillStrokeEvenOdd,
        CloseFillStrokeNonzero,
        CloseFillStrokeEvenOdd,
        EndPath,
        ClipPathNonzero,
        ClipPathEvenOdd,
        BeginText,
        EndText,
        CharacterSpacing,
        WordSpacing,
        HorizontalScaling,
        Leading,
        TextFont,
        TextRenderingMode,
        TextRise,
        TextTranslate,
        TextTranslateLeading,
        TextMatrix,
        TextNextLine,
        TextShow,
        TextShowArray,
        TextNextLineShow,
        TextNextLineShowSpacing,
        SetCharWidth,
        SetCacheDevice,
        ColorSpaceStroke,
        ColorSpaceNonstroke,
        SetColorStroke,
        SetColorStrokeExtended,
        SetColorNonstroke,
        SetColorNonstrokeExtended,
        SetStrokingColorSpaceGray,
        SetNonstrokingColorSpaceGray,
        SetStrokingColorSpaceRGB,
        SetNonstrokingColorSpaceRGB,
        SetStrokingColorSpaceCMYK,
        SetNonstrokingColorSpaceCMYK,
        ShadingPaint,
        BeginInlineImageObject,
        BeginInlineImageData,
        EndInlineImageObject,
        InvokeXObject,
        DefineMarkedContentPoint,
        DefineMarkedContentPointWithPropertyList,
        BeginMarkedContentSequence,
        BeginMarkedContentSequenceWithPropertyList,
        EndMarkedContentSequence,
        BeginCompatibilitySection,
        EndCompatibilitySection
    };
}
